-- ============================================================
-- 02_tables.sql
-- Creates all IntelliDoc tables.
-- Run after 01_database_schema.sql.
--
-- CLIENT_ACCOUNT_ID = Snowflake reader account name used for
-- CURRENT_ACCOUNT() isolation in Secure Views and search.
-- Populated at routing time from CLIENT_MAPPING, not at ingestion.
-- ============================================================

USE DATABASE INTELLIDOC_DB;
USE SCHEMA   INTELLIDOC_DB.INTELLIDOC;
USE WAREHOUSE INTELLIDOC_WH;

-- ── DOCUMENT_REGISTRY ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS DOCUMENT_REGISTRY (
    FILE_ID             VARCHAR(36)   NOT NULL,
    FILE_NAME           VARCHAR(512)  NOT NULL,
    FILE_FORMAT         VARCHAR(10)   NOT NULL,   -- PDF | XLSX | CSV
    CLIENT_ACCOUNT_ID   VARCHAR(64),              -- reader account name; set at routing via CLIENT_MAPPING
    ACCOUNT_ID          VARCHAR(64)   NOT NULL,   -- from metadata (Accountid)
    BRANCH_ID           VARCHAR(64)   NOT NULL,   -- from metadata (branch_id)
    DOCUMENT_TYPE       VARCHAR(64),              -- LLM-assigned after classification
    FILE_HASH           VARCHAR(64)   NOT NULL,   -- SHA-256
    FILE_SIZE           NUMBER        NOT NULL,
    CURRENT_LOCATION    VARCHAR(256),             -- stage path
    PROCESSING_STATUS   VARCHAR(32)   NOT NULL DEFAULT 'RECEIVED',
    SOURCE_SYSTEM       VARCHAR(64),
    CREATED_TS          TIMESTAMP_NTZ NOT NULL DEFAULT SYSDATE(),
    UPDATED_TS          TIMESTAMP_NTZ NOT NULL DEFAULT SYSDATE(),
    CONSTRAINT PK_DOCUMENT_REGISTRY PRIMARY KEY (FILE_ID)
);

-- ── DOCUMENT_CHUNKS ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS DOCUMENT_CHUNKS (
    CHUNK_ID          NUMBER IDENTITY(1,1) NOT NULL,
    FILE_ID           VARCHAR(36)    NOT NULL,
    CLIENT_ACCOUNT_ID VARCHAR(64)    NOT NULL,    -- reader account; filter on every search
    CHUNK_INDEX       NUMBER         NOT NULL,
    CHUNK_TEXT        VARCHAR(8000)  NOT NULL,
    EMBEDDING         VECTOR(FLOAT, 1024),
    TOKEN_COUNT       NUMBER,
    CREATED_TS        TIMESTAMP_NTZ  NOT NULL DEFAULT SYSDATE(),
    CONSTRAINT PK_DOCUMENT_CHUNKS PRIMARY KEY (CHUNK_ID),
    CONSTRAINT FK_CHUNKS_REGISTRY FOREIGN KEY (FILE_ID)
        REFERENCES DOCUMENT_REGISTRY(FILE_ID)
);

-- ── DOCUMENT_CLASSIFICATION ───────────────────────────────────
CREATE TABLE IF NOT EXISTS DOCUMENT_CLASSIFICATION (
    FILE_ID                    VARCHAR(36)   NOT NULL,
    DOCUMENT_TYPE              VARCHAR(64)   NOT NULL,
    CLASSIFICATION_CONFIDENCE  VARCHAR(16),
    KEY_INDICATORS             VARCHAR(2000),
    DOC_SUMMARY                VARCHAR(2000),
    MODEL_NAME                 VARCHAR(64),
    CLASSIFIED_TS              TIMESTAMP_NTZ NOT NULL DEFAULT SYSDATE(),
    CONSTRAINT PK_DOCUMENT_CLASSIFICATION PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_CLASS_REGISTRY FOREIGN KEY (FILE_ID)
        REFERENCES DOCUMENT_REGISTRY(FILE_ID)
);

-- ── CLIENT_MAPPING ────────────────────────────────────────────
-- PK = ACCOUNT_ID + BRANCH_ID (from metadata).
-- CLIENT_ACCOUNT_ID = Snowflake reader account name; used in
-- Secure Views as CURRENT_ACCOUNT() isolation filter.
CREATE TABLE IF NOT EXISTS CLIENT_MAPPING (
    ACCOUNT_ID          VARCHAR(64)   NOT NULL,
    BRANCH_ID           VARCHAR(64)   NOT NULL,
    CLIENT_NAME         VARCHAR(256),
    CLIENT_ACCOUNT_ID   VARCHAR(128)  NOT NULL,   -- reader account name e.g. APEX_READER
    CLIENT_STAGE_NAME   VARCHAR(128),             -- internal stage routing target
    ACTIVE_FLAG         BOOLEAN       NOT NULL DEFAULT TRUE,
    CREATED_TS          TIMESTAMP_NTZ NOT NULL DEFAULT SYSDATE(),
    CONSTRAINT PK_CLIENT_MAPPING PRIMARY KEY (ACCOUNT_ID, BRANCH_ID)
);

-- ── DOCUMENT_PROCESSING_AUDIT ─────────────────────────────────
CREATE TABLE IF NOT EXISTS DOCUMENT_PROCESSING_AUDIT (
    AUDIT_ID      NUMBER IDENTITY(1,1) NOT NULL,
    FILE_ID       VARCHAR(36)   NOT NULL,
    STEP_NAME     VARCHAR(64)   NOT NULL,
    STATUS        VARCHAR(32)   NOT NULL,
    START_TS      TIMESTAMP_NTZ,
    END_TS        TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR(4000),
    CONSTRAINT PK_AUDIT PRIMARY KEY (AUDIT_ID)
);

-- ── SEARCH_AUDIT ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS SEARCH_AUDIT (
    SEARCH_ID         NUMBER IDENTITY(1,1) NOT NULL,
    CLIENT_ACCOUNT_ID VARCHAR(64)   NOT NULL,     -- reader account that ran the search
    SEARCH_TERM       VARCHAR(2000) NOT NULL,
    RESULT_FILE_ID    VARCHAR(36),
    SEARCH_CONFIDENCE VARCHAR(16),
    RESULT_COUNT      NUMBER,
    EXECUTION_TIME_MS NUMBER,
    SEARCH_TS         TIMESTAMP_NTZ NOT NULL DEFAULT SYSDATE(),
    CONSTRAINT PK_SEARCH_AUDIT PRIMARY KEY (SEARCH_ID)
);

-- ── CLIENT_MAPPING seed rows ──────────────────────────────────
-- CLIENT_ACCOUNT_ID = Snowflake reader account name.
-- Replace placeholder names with actual reader account identifiers.
INSERT INTO CLIENT_MAPPING
    (ACCOUNT_ID, BRANCH_ID, CLIENT_NAME, CLIENT_ACCOUNT_ID, CLIENT_STAGE_NAME, ACTIVE_FLAG)
VALUES
    ('GB-CUST-00421', 'BRANCH-GLOBALBANK', 'Apex Pension Fund LLC',     'APEX_READER',     'APEX_STAGE',     TRUE),
    ('GB-CUST-00532', 'BRANCH-GLOBALBANK', 'Meridian Asset Management', 'MERIDIAN_READER', 'MERIDIAN_STAGE', TRUE),
    ('GB-CUST-00615', 'BRANCH-GLOBALBANK', 'Summit Endowment Fund',     'SUMMIT_READER',   'SUMMIT_STAGE',   TRUE);

-- Verify
DESCRIBE TABLE DOCUMENT_REGISTRY;
DESCRIBE TABLE DOCUMENT_CHUNKS;
DESCRIBE TABLE DOCUMENT_CLASSIFICATION;
DESCRIBE TABLE CLIENT_MAPPING;
DESCRIBE TABLE DOCUMENT_PROCESSING_AUDIT;
DESCRIBE TABLE SEARCH_AUDIT;
